feat KPI-227 improve user page pagination
kpinetwork/backend pull request #202
Opened 2022-09-15 22:05 UTC by FreddyJR1995

## Jira Link

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-227)

## Types of changes

- [ ] Hotfix (Bug detected)
- [x] Feature (Issue from an Active Sprint)

## Checklist:

- [x] Unit Test.
- [x] Coverage.

## Solution

2022-09-16 20:20 UTC, kellycastrof requested changes

2022-09-16 20:20 UTC, kellycastrof commented on infrastructure/policy/iam.tf
> +        "cognito-id:ListUsersInGroup"
I think this should be codnito-idp instead of cognito-id

2022-09-16 20:20 UTC, kellycastrof commented on src/service/users/users_service.py
> +        print("token", response)
Remove this

2022-09-16 20:20 UTC, kellycastrof commented on infrastructure/network/gateways.tf
> +    "method.request.querystring.group" = false
This should be mandatory

2022-09-21 22:00 UTC, dsgarcia8 requested changes

2022-09-22 13:59 UTC, FreddyJR1995 commented on src/handlers/users/get_users_handler.py
> +        group = "demo_customer_group"
variable added and value changed

2022-09-27 14:48 UTC, dsgarcia8 approved these changes

2022-09-29 16:48 UTC, kellycastrof approved these changes

2022-09-29 16:51 UTC, merged