feat: KPI-272 get tags by company id
kpinetwork/backend pull request #225
Opened 2022-10-12 20:57 UTC by dsgarcia8

## Jira Link

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-XXX)

## Types of changes

- [ ] Hotfix (Bug detected)
- [x] Feature (Issue from an Active Sprint)

## Checklist:

- [x] Unit Test.
- [x] Coverage.

## Solution

2022-10-12 21:44 UTC, kellycastrof requested changes

2022-10-12 21:44 UTC, kellycastrof commented on src/service/tags/tags_service.py
> +            return self.repository.get_tags_by_company(company_id)
You can move the validation of the company_id here and raise an exception instead of returning the empty value.

2022-10-13 20:05 UTC, FreddyJR1995 approved these changes

2022-10-14 13:15 UTC, kellycastrof approved these changes

2022-10-17 16:55 UTC, merged