Kpi 54 create lambdas to retrieve information
kpinetwork/backend pull request #33
Opened 2021-11-08 15:42 UTC by ridouku

## Jira Link

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-XXX)

## Types of changes

- [ ] Hotfix (Bug detected)
- [x] Feature (Issue from an Active Sprint)

## Checklist:

- [x] Unit Test.
- [ ] Coverage.

## Solution

2021-11-09 17:11 UTC, kellycastrof requested changes

2021-11-09 17:11 UTC, kellycastrof commented on src/service/metrics/metrics_service.py
> +            [metrics.append(dict(record)) for record in results]
I think we can use a function to process the records similar to process_query_results

2021-11-09 17:11 UTC, kellycastrof commented on src/service/metrics/metrics_service.py
> +    def get_metric_by_id(self, metric_id: str) -> dict:
Change to get metrics by a company id

2021-11-10 15:39 UTC, ridouku commented on src/utils/response_sql.py
> +            return dict()
Validate this before the loop

2021-11-10 20:22 UTC, kellycastrof approved these changes

2021-11-10 20:49 UTC, merged