feat: KPI-19-terraform-implementations-with-github-actions
kpinetwork/backend pull request #5
Opened 2021-09-06 22:01 UTC by ridouku

## Jira Link

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-XXX)

## Types of changes

- [ ] Hotfix (Bug detected)
- [x] Feature (Issue from an Active Sprint)

## Checklist:

- [ ] Unit Test.
- [ ] Coverage.

## Solution

2021-09-08 15:00 UTC, herrera-luis commented on infrasctructure/permissions.tf
> +# ----------------------------------------------------------------------------------------------------------------------
i think that this file should be rename to: iam.tf instead of permissions.tf

2021-09-08 15:01 UTC, herrera-luis requested changes
great PR, let's structure the infrastructure resources using generic directories for each resources for example:
infrastructure/logs/cloudwatch.tf
infrastructure/nosql/dynamodb.tf
infrastructure/network/gateways.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/policy/iam.tf

So the main file will live at the root of the infrastructure folder and each resource in their respective folder.

infrastructure/main.tf

Maybe this repository could be used as a guide:
https://github.com/kpinetwork/infrastructure

2021-09-10 22:43 UTC, herrera-luis approved these changes

2021-09-10 22:43 UTC, kellycastrof approved these changes

2021-09-14 17:31 UTC, kellycastrof approved these changes
Good job 👍

2021-09-14 19:04 UTC, merged